import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./components/NavBar";
import { Suspense } from "react";
import AuthProvider from "./auth/Provider";
import { Poppins, Roboto} from "next/font/google"

const poppins = Poppins({
  subsets: ['latin-ext'],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-poppins",
  
})
const roboto = Roboto({
  subsets: ['latin-ext'],
  display: "swap",
  weight: ["400", "700"],
  variable: "--font-poppins",
  
})

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
  
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme ='winter'>
      <body
        className={poppins.className}
      >
        <AuthProvider>
        <NavBar/>
        <main className="p-5">
        <Suspense fallback={<span className="loading loading-dots loading-lg"></span>}>
          {children}
        </Suspense>
        </main>
        </AuthProvider>
      </body>
    </html>
  );
}
